-- 코드를 작성해주세요
SELECT e.ID, COALESCE(PARENT_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA e
LEFT JOIN (
    SELECT PARENT_ID, COUNT(*) AS PARENT_count
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) c ON e.ID = c.PARENT_ID
ORDER BY e.ID;
