-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(K.SALES) AS TOTAL_SALES
FROM BOOK B
INNER JOIN BOOK_SALES K
ON B.BOOK_ID = K.BOOK_ID
WHERE TO_CHAR(K.SALES_DATE,'YYYY-MM') = '2022-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC