-- 코드를 작성해주세요
WITH z AS (
    SELECT * ,
        CASE 
            WHEN LENGTH IS NULL THEN 10
            ELSE LENGTH
        END AS LENGTH1
    FROM fish_info
)

SELECT  COUNT(*) AS FISH_COUNT
    ,   MAX(LENGTH1) AS MAX_LENGTH
    ,   FISH_TYPE
FROM Z
GROUP BY FISH_TYPE
HAVING AVG(LENGTH1)>=33
ORDER BY FISH_TYPE
;